---
swagger: '2.0'
info:
  title: API V1
  version: v1
definitions:
  createUser:
    type: object
    properties:
      name:
        type: string
        example: Leslie Knope
      dob:
        type: string
        example: '1975-1-1'
      email:
        type: string
        example: lilsebastian1975@lycos.com
      ident_num:
        type: string
        example: S1128628
      ident_state:
        type: string
        example: IN
      ident_expir:
        type: string
        example: '2025-1-1'
      ident_img:
        type: string
        example: image.jpg
      recom_num:
        type: string
        example: '32823493'
      recom_issuer:
        type: string
        example: Dr. Ron Burgundy
      recom_expir:
        type: string
        example: '2023-1-1'
      recom_img:
        type: string
        example: image.jpg
    required:
    - name
    - email
    - dob
  showUser:
    type: object
    properties:
      id:
        type: number
        example: 1
      name:
        type: string
        example: Leslie Knope
      dob:
        type: string
        example: '1975-1-1'
      email:
        type: string
        example: lilsebastian1975@lycos.com
      ident_num:
        type: string
        example: S1128628
      ident_state:
        type: string
        example: IN
      ident_expir:
        type: string
        example: '2025-1-1'
      ident_img:
        type: string
        example: image.jpg
      recom_num:
        type: string
        example: '32823493'
      recom_issuer:
        type: string
        example: Dr. Ron Burgundy
      recom_expir:
        type: string
        example: '2020-1-1'
      recom_img:
        type: string
        example: image.jpg
      status:
        type: string
        example: EXPIRED
    required:
    - name
    - email
    - dob
paths:
  "/api/v1/users":
    post:
      summary: Creates a new user
      tags:
      - users
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          "$ref": "#/definitions/createUser"
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
    get:
      summary: Retrieves all users
      tags:
      - users
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        '200':
          description: list users
          schema:
            type: array
            items:
              "$ref": "#/definitions/showUser"
  "/api/v1/users/{user_id}":
    get:
      summary: Retrieves a user
      tags:
      - users
      consumes:
      - application/json
      parameters:
      - name: user_id
        in: path
        type: string
        required: true
      produces:
      - application/json
      responses:
        '200':
          description: user found
          schema:
            type: object
            properties:
              "$ref": "#/definitions/showUser"
        '404':
          description: user not found
        '406':
          description: unsupported accept header
    put:
      summary: Update a user
      tags:
      - users
      consumes:
      - application/json
      parameters:
      - name: user_id
        in: path
        type: string
        required: true
      - name: user
        in: body
        schema:
          "$ref": "#/definitions/createUser"
      produces:
      - application/json
      responses:
        '200':
          description: user updated
        '404':
          description: user not found
    delete:
      summary: Delete a user
      tags:
      - users
      consumes:
      - application/json
      parameters:
      - name: user_id
        in: path
        type: string
        required: true
      produces:
      - application/json
      responses:
        '204':
          description: user deleted
        '404':
          description: user not found
